# Generated by Django 3.1.3 on 2020-12-01 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_auto_20201201_0738'),
        ('posts', '0012_auto_20201201_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, through='posts.Like', to='likes.Like'),
        ),
    ]
